name: Deploy Lambda

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set environment variables based on branch
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "API_KEY=prod_api_key" >> $GITHUB_ENV
            echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
          else
            echo "ENV=test" >> $GITHUB_ENV
            echo "API_KEY=test_api_key" >> $GITHUB_ENV
            echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
          fi

      # 3️⃣ Install basic utilities
      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip

      # 4️⃣ Package Lambda dependencies inside the AWS Lambda Python 3.11 Docker image
      - name: Package Lambda Function on Amazon Linux (x86_64)
        run: |
          set -euo pipefail
          cd lambda_function

          rm -rf build package python deps.zip ../lambda.zip || true

          docker run --rm \
            --platform linux/amd64 \
            --entrypoint /bin/bash \
            -v "$PWD":/var/task \
            public.ecr.aws/lambda/python:3.11 \
            -lc "
              set -e
              yum install -y zip >/dev/null
              python -m pip install --upgrade pip
              mkdir -p python
              # install pandas, requests and their dependencies using binary wheels
              pip install --root-user-action=ignore --only-binary=:all: -r requirements.txt -t python
              cd /var/task
              zip -r ../deps.zip python
            "

          # Combine dependencies + Lambda handler
          mkdir -p package
          unzip -q ../deps.zip -d package
          cp app.py package/

          # Move dependencies to root (important for Lambda)
          if [ -d "package/python" ]; then
            mv package/python/* package/
            rm -rf package/python
          fi

          cd package
          zip -r ../../lambda.zip .
          cd ../..

      # 5️⃣ Configure AWS credentials (secure from GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6️⃣ Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          REGION: us-east-1
        run: |
          set -euo pipefail
          FUNCTION_NAME="cicd_lambda_${{ github.ref_name }}"
          ENV_VARS="Variables={ENV=${{ env.ENV }},API_KEY=${{ env.API_KEY }},LOG_LEVEL=${{ env.LOG_LEVEL }}}"

          echo "Deploying Lambda function: $FUNCTION_NAME in $REGION"

          if ! aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" >/dev/null 2>&1; then
            echo "Creating new function: $FUNCTION_NAME ..."
            aws lambda create-function \
              --function-name "$FUNCTION_NAME" \
              --runtime python3.11 \
              --architecture x86_64 \
              --role arn:aws:iam::114498380988:role/test_lambda_dev \
              --handler app.lambda_handler \
              --timeout 300 \
              --zip-file fileb://lambda.zip \
              --region "$REGION" \
              --environment "$ENV_VARS"

            echo "Waiting for Lambda creation to finish..."
            aws lambda wait function-active --function-name "$FUNCTION_NAME" --region "$REGION"
          else
            echo "Updating code for existing function: $FUNCTION_NAME ..."
            aws lambda update-function-code \
              --function-name "$FUNCTION_NAME" \
              --zip-file fileb://lambda.zip \
              --region "$REGION" >/dev/null

            echo "Waiting for code update..."
            aws lambda wait function-updated --function-name "$FUNCTION_NAME" --region "$REGION"

            echo "Updating configuration..."
            aws lambda update-function-configuration \
              --function-name "$FUNCTION_NAME" \
              --environment "$ENV_VARS" \
              --region "$REGION" >/dev/null

            echo "Waiting for configuration update..."
            aws lambda wait function-updated --function-name "$FUNCTION_NAME" --region "$REGION"
          fi
